version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sidequest-db
    environment:
      MYSQL_ROOT_PASSWORD: aditya123123
      MYSQL_DATABASE: sidequest_board
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: sidequest-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sidequest_board?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: aditya123123
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: sidequest-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
