# Auto-generated by Jenkinsfile.infra — do not edit manually.
# Last baked: 38
aws_region       = "eu-north-1"
instance_type    = "t3.small"
ami_id           = "ami-0f7e7c999f18064f8"
key_name         = "ec2-key"
ssh_allowed_cidr = ["0.0.0.0/0"]
