# Auto-generated by Jenkinsfile.infra — do not edit manually.
# Last baked: 39
aws_region       = "eu-north-1"
instance_type    = "t3.small"
ami_id           = "ami-0f0e7c7d9bebc09ad"
key_name         = "ec2-key"
ssh_allowed_cidr = ["0.0.0.0/0"]
